// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package agent

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIAgent creates a new instance of MockIAgent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAgent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAgent {
	mock := &MockIAgent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAgent is an autogenerated mock type for the IAgent type
type MockIAgent struct {
	mock.Mock
}

type MockIAgent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAgent) EXPECT() *MockIAgent_Expecter {
	return &MockIAgent_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIAgent
func (_mock *MockIAgent) Create(ctx context.Context, params CreateAgentParams) (*CreateAgentResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *CreateAgentResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateAgentParams) (*CreateAgentResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateAgentParams) *CreateAgentResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateAgentResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateAgentParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAgent_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAgent_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - params CreateAgentParams
func (_e *MockIAgent_Expecter) Create(ctx any, params any) *MockIAgent_Create_Call {
	return &MockIAgent_Create_Call{Call: _e.mock.On("Create", ctx, params)}
}

func (_c *MockIAgent_Create_Call) Run(run func(ctx context.Context, params CreateAgentParams)) *MockIAgent_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateAgentParams
		if args[1] != nil {
			arg1 = args[1].(CreateAgentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgent_Create_Call) Return(createAgentResult *CreateAgentResult, err error) *MockIAgent_Create_Call {
	_c.Call.Return(createAgentResult, err)
	return _c
}

func (_c *MockIAgent_Create_Call) RunAndReturn(run func(ctx context.Context, params CreateAgentParams) (*CreateAgentResult, error)) *MockIAgent_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIAgent
func (_mock *MockIAgent) Delete(ctx context.Context, params DeleteAgentParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, DeleteAgentParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAgent_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIAgent_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - params DeleteAgentParams
func (_e *MockIAgent_Expecter) Delete(ctx any, params any) *MockIAgent_Delete_Call {
	return &MockIAgent_Delete_Call{Call: _e.mock.On("Delete", ctx, params)}
}

func (_c *MockIAgent_Delete_Call) Run(run func(ctx context.Context, params DeleteAgentParams)) *MockIAgent_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DeleteAgentParams
		if args[1] != nil {
			arg1 = args[1].(DeleteAgentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgent_Delete_Call) Return(err error) *MockIAgent_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAgent_Delete_Call) RunAndReturn(run func(ctx context.Context, params DeleteAgentParams) error) *MockIAgent_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnalytics provides a mock function for the type MockIAgent
func (_mock *MockIAgent) GetAnalytics(ctx context.Context, params GetAnalyticsParams) ([]ConversationAnalytics, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalytics")
	}

	var r0 []ConversationAnalytics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, GetAnalyticsParams) ([]ConversationAnalytics, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, GetAnalyticsParams) []ConversationAnalytics); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ConversationAnalytics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, GetAnalyticsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAgent_GetAnalytics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnalytics'
type MockIAgent_GetAnalytics_Call struct {
	*mock.Call
}

// GetAnalytics is a helper method to define mock.On call
//   - ctx context.Context
//   - params GetAnalyticsParams
func (_e *MockIAgent_Expecter) GetAnalytics(ctx any, params any) *MockIAgent_GetAnalytics_Call {
	return &MockIAgent_GetAnalytics_Call{Call: _e.mock.On("GetAnalytics", ctx, params)}
}

func (_c *MockIAgent_GetAnalytics_Call) Run(run func(ctx context.Context, params GetAnalyticsParams)) *MockIAgent_GetAnalytics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 GetAnalyticsParams
		if args[1] != nil {
			arg1 = args[1].(GetAnalyticsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgent_GetAnalytics_Call) Return(conversationAnalyticss []ConversationAnalytics, err error) *MockIAgent_GetAnalytics_Call {
	_c.Call.Return(conversationAnalyticss, err)
	return _c
}

func (_c *MockIAgent_GetAnalytics_Call) RunAndReturn(run func(ctx context.Context, params GetAnalyticsParams) ([]ConversationAnalytics, error)) *MockIAgent_GetAnalytics_Call {
	_c.Call.Return(run)
	return _c
}

// GetConversation provides a mock function for the type MockIAgent
func (_mock *MockIAgent) GetConversation(ctx context.Context, params GetConversationParams) (*ConversationAnalytics, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetConversation")
	}

	var r0 *ConversationAnalytics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, GetConversationParams) (*ConversationAnalytics, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, GetConversationParams) *ConversationAnalytics); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ConversationAnalytics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, GetConversationParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAgent_GetConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConversation'
type MockIAgent_GetConversation_Call struct {
	*mock.Call
}

// GetConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - params GetConversationParams
func (_e *MockIAgent_Expecter) GetConversation(ctx any, params any) *MockIAgent_GetConversation_Call {
	return &MockIAgent_GetConversation_Call{Call: _e.mock.On("GetConversation", ctx, params)}
}

func (_c *MockIAgent_GetConversation_Call) Run(run func(ctx context.Context, params GetConversationParams)) *MockIAgent_GetConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 GetConversationParams
		if args[1] != nil {
			arg1 = args[1].(GetConversationParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgent_GetConversation_Call) Return(conversationAnalytics *ConversationAnalytics, err error) *MockIAgent_GetConversation_Call {
	_c.Call.Return(conversationAnalytics, err)
	return _c
}

func (_c *MockIAgent_GetConversation_Call) RunAndReturn(run func(ctx context.Context, params GetConversationParams) (*ConversationAnalytics, error)) *MockIAgent_GetConversation_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecordings provides a mock function for the type MockIAgent
func (_mock *MockIAgent) GetRecordings(ctx context.Context, params GetRecordingsParams) ([]ConversationRecording, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetRecordings")
	}

	var r0 []ConversationRecording
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, GetRecordingsParams) ([]ConversationRecording, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, GetRecordingsParams) []ConversationRecording); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ConversationRecording)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, GetRecordingsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAgent_GetRecordings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecordings'
type MockIAgent_GetRecordings_Call struct {
	*mock.Call
}

// GetRecordings is a helper method to define mock.On call
//   - ctx context.Context
//   - params GetRecordingsParams
func (_e *MockIAgent_Expecter) GetRecordings(ctx any, params any) *MockIAgent_GetRecordings_Call {
	return &MockIAgent_GetRecordings_Call{Call: _e.mock.On("GetRecordings", ctx, params)}
}

func (_c *MockIAgent_GetRecordings_Call) Run(run func(ctx context.Context, params GetRecordingsParams)) *MockIAgent_GetRecordings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 GetRecordingsParams
		if args[1] != nil {
			arg1 = args[1].(GetRecordingsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgent_GetRecordings_Call) Return(conversationRecordings []ConversationRecording, err error) *MockIAgent_GetRecordings_Call {
	_c.Call.Return(conversationRecordings, err)
	return _c
}

func (_c *MockIAgent_GetRecordings_Call) RunAndReturn(run func(ctx context.Context, params GetRecordingsParams) ([]ConversationRecording, error)) *MockIAgent_GetRecordings_Call {
	_c.Call.Return(run)
	return _c
}
