// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package phonenumber

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIPhoneNumberManager creates a new instance of MockIPhoneNumberManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPhoneNumberManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPhoneNumberManager {
	mock := &MockIPhoneNumberManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPhoneNumberManager is an autogenerated mock type for the IPhoneNumberManager type
type MockIPhoneNumberManager struct {
	mock.Mock
}

type MockIPhoneNumberManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPhoneNumberManager) EXPECT() *MockIPhoneNumberManager_Expecter {
	return &MockIPhoneNumberManager_Expecter{mock: &_m.Mock}
}

// CheckAvailable provides a mock function for the type MockIPhoneNumberManager
func (_mock *MockIPhoneNumberManager) CheckAvailable(ctx context.Context, params CheckAvailableParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CheckAvailable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CheckAvailableParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPhoneNumberManager_CheckAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAvailable'
type MockIPhoneNumberManager_CheckAvailable_Call struct {
	*mock.Call
}

// CheckAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - params CheckAvailableParams
func (_e *MockIPhoneNumberManager_Expecter) CheckAvailable(ctx any, params any) *MockIPhoneNumberManager_CheckAvailable_Call {
	return &MockIPhoneNumberManager_CheckAvailable_Call{Call: _e.mock.On("CheckAvailable", ctx, params)}
}

func (_c *MockIPhoneNumberManager_CheckAvailable_Call) Run(run func(ctx context.Context, params CheckAvailableParams)) *MockIPhoneNumberManager_CheckAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CheckAvailableParams
		if args[1] != nil {
			arg1 = args[1].(CheckAvailableParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPhoneNumberManager_CheckAvailable_Call) Return(err error) *MockIPhoneNumberManager_CheckAvailable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPhoneNumberManager_CheckAvailable_Call) RunAndReturn(run func(ctx context.Context, params CheckAvailableParams) error) *MockIPhoneNumberManager_CheckAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// ListAvailable provides a mock function for the type MockIPhoneNumberManager
func (_mock *MockIPhoneNumberManager) ListAvailable(ctx context.Context, params ListAvailablePhoneNumbersParams) ([]AvailablePhoneNumber, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailable")
	}

	var r0 []AvailablePhoneNumber
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListAvailablePhoneNumbersParams) ([]AvailablePhoneNumber, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListAvailablePhoneNumbersParams) []AvailablePhoneNumber); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AvailablePhoneNumber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ListAvailablePhoneNumbersParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPhoneNumberManager_ListAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAvailable'
type MockIPhoneNumberManager_ListAvailable_Call struct {
	*mock.Call
}

// ListAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - params ListAvailablePhoneNumbersParams
func (_e *MockIPhoneNumberManager_Expecter) ListAvailable(ctx any, params any) *MockIPhoneNumberManager_ListAvailable_Call {
	return &MockIPhoneNumberManager_ListAvailable_Call{Call: _e.mock.On("ListAvailable", ctx, params)}
}

func (_c *MockIPhoneNumberManager_ListAvailable_Call) Run(run func(ctx context.Context, params ListAvailablePhoneNumbersParams)) *MockIPhoneNumberManager_ListAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ListAvailablePhoneNumbersParams
		if args[1] != nil {
			arg1 = args[1].(ListAvailablePhoneNumbersParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPhoneNumberManager_ListAvailable_Call) Return(availablePhoneNumbers []AvailablePhoneNumber, err error) *MockIPhoneNumberManager_ListAvailable_Call {
	_c.Call.Return(availablePhoneNumbers, err)
	return _c
}

func (_c *MockIPhoneNumberManager_ListAvailable_Call) RunAndReturn(run func(ctx context.Context, params ListAvailablePhoneNumbersParams) ([]AvailablePhoneNumber, error)) *MockIPhoneNumberManager_ListAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// ListPurchased provides a mock function for the type MockIPhoneNumberManager
func (_mock *MockIPhoneNumberManager) ListPurchased(ctx context.Context) ([]PurchasedPhoneNumber, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPurchased")
	}

	var r0 []PurchasedPhoneNumber
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]PurchasedPhoneNumber, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []PurchasedPhoneNumber); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PurchasedPhoneNumber)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPhoneNumberManager_ListPurchased_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPurchased'
type MockIPhoneNumberManager_ListPurchased_Call struct {
	*mock.Call
}

// ListPurchased is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIPhoneNumberManager_Expecter) ListPurchased(ctx any) *MockIPhoneNumberManager_ListPurchased_Call {
	return &MockIPhoneNumberManager_ListPurchased_Call{Call: _e.mock.On("ListPurchased", ctx)}
}

func (_c *MockIPhoneNumberManager_ListPurchased_Call) Run(run func(ctx context.Context)) *MockIPhoneNumberManager_ListPurchased_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPhoneNumberManager_ListPurchased_Call) Return(purchasedPhoneNumbers []PurchasedPhoneNumber, err error) *MockIPhoneNumberManager_ListPurchased_Call {
	_c.Call.Return(purchasedPhoneNumbers, err)
	return _c
}

func (_c *MockIPhoneNumberManager_ListPurchased_Call) RunAndReturn(run func(ctx context.Context) ([]PurchasedPhoneNumber, error)) *MockIPhoneNumberManager_ListPurchased_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function for the type MockIPhoneNumberManager
func (_mock *MockIPhoneNumberManager) Reserve(ctx context.Context, params ReservePhoneNumberParams) (*ReservePhoneNumberResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 *ReservePhoneNumberResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ReservePhoneNumberParams) (*ReservePhoneNumberResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ReservePhoneNumberParams) *ReservePhoneNumberResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReservePhoneNumberResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ReservePhoneNumberParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPhoneNumberManager_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type MockIPhoneNumberManager_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx context.Context
//   - params ReservePhoneNumberParams
func (_e *MockIPhoneNumberManager_Expecter) Reserve(ctx any, params any) *MockIPhoneNumberManager_Reserve_Call {
	return &MockIPhoneNumberManager_Reserve_Call{Call: _e.mock.On("Reserve", ctx, params)}
}

func (_c *MockIPhoneNumberManager_Reserve_Call) Run(run func(ctx context.Context, params ReservePhoneNumberParams)) *MockIPhoneNumberManager_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ReservePhoneNumberParams
		if args[1] != nil {
			arg1 = args[1].(ReservePhoneNumberParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPhoneNumberManager_Reserve_Call) Return(reservePhoneNumberResult *ReservePhoneNumberResult, err error) *MockIPhoneNumberManager_Reserve_Call {
	_c.Call.Return(reservePhoneNumberResult, err)
	return _c
}

func (_c *MockIPhoneNumberManager_Reserve_Call) RunAndReturn(run func(ctx context.Context, params ReservePhoneNumberParams) (*ReservePhoneNumberResult, error)) *MockIPhoneNumberManager_Reserve_Call {
	_c.Call.Return(run)
	return _c
}
