template: testify
formatter: goimports
force-file-write: true

packages:
  github.com/ali-gulzar/speechory-core/internal/services:
    config:
      all: true
      recursive: true
      dir: "{{.InterfaceDir}}"
      filename: "{{.InterfaceFile | base | trimSuffix \".go\"}}_mock.go"
      pkgname: "{{.SrcPackageName}}"
      structname: "{{.Mock}}{{.InterfaceName}}"