// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tool

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockITool creates a new instance of MockITool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITool {
	mock := &MockITool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITool is an autogenerated mock type for the ITool type
type MockITool struct {
	mock.Mock
}

type MockITool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITool) EXPECT() *MockITool_Expecter {
	return &MockITool_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockITool
func (_mock *MockITool) List(ctx context.Context) ([]ListToolsResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []ListToolsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ListToolsResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ListToolsResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ListToolsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITool_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockITool_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockITool_Expecter) List(ctx any) *MockITool_List_Call {
	return &MockITool_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockITool_List_Call) Run(run func(ctx context.Context)) *MockITool_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockITool_List_Call) Return(listToolsResults []ListToolsResult, err error) *MockITool_List_Call {
	_c.Call.Return(listToolsResults, err)
	return _c
}

func (_c *MockITool_List_Call) RunAndReturn(run func(ctx context.Context) ([]ListToolsResult, error)) *MockITool_List_Call {
	_c.Call.Return(run)
	return _c
}
