// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIAuth creates a new instance of MockIAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAuth {
	mock := &MockIAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAuth is an autogenerated mock type for the IAuth type
type MockIAuth struct {
	mock.Mock
}

type MockIAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAuth) EXPECT() *MockIAuth_Expecter {
	return &MockIAuth_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockIAuth
func (_mock *MockIAuth) Authenticate(ctx context.Context, accessToken string) (*AuthenticatedUser, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *AuthenticatedUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*AuthenticatedUser, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *AuthenticatedUser); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthenticatedUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAuth_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockIAuth_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockIAuth_Expecter) Authenticate(ctx any, accessToken any) *MockIAuth_Authenticate_Call {
	return &MockIAuth_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, accessToken)}
}

func (_c *MockIAuth_Authenticate_Call) Run(run func(ctx context.Context, accessToken string)) *MockIAuth_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAuth_Authenticate_Call) Return(authenticatedUser *AuthenticatedUser, err error) *MockIAuth_Authenticate_Call {
	_c.Call.Return(authenticatedUser, err)
	return _c
}

func (_c *MockIAuth_Authenticate_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (*AuthenticatedUser, error)) *MockIAuth_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Invite provides a mock function for the type MockIAuth
func (_mock *MockIAuth) Invite(ctx context.Context, email string) (*InviteResult, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Invite")
	}

	var r0 *InviteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*InviteResult, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *InviteResult); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*InviteResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAuth_Invite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invite'
type MockIAuth_Invite_Call struct {
	*mock.Call
}

// Invite is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIAuth_Expecter) Invite(ctx any, email any) *MockIAuth_Invite_Call {
	return &MockIAuth_Invite_Call{Call: _e.mock.On("Invite", ctx, email)}
}

func (_c *MockIAuth_Invite_Call) Run(run func(ctx context.Context, email string)) *MockIAuth_Invite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAuth_Invite_Call) Return(inviteResult *InviteResult, err error) *MockIAuth_Invite_Call {
	_c.Call.Return(inviteResult, err)
	return _c
}

func (_c *MockIAuth_Invite_Call) RunAndReturn(run func(ctx context.Context, email string) (*InviteResult, error)) *MockIAuth_Invite_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockIAuth
func (_mock *MockIAuth) RefreshToken(ctx context.Context, refreshToken string) (*SignInResult, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *SignInResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*SignInResult, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *SignInResult); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SignInResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAuth_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockIAuth_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockIAuth_Expecter) RefreshToken(ctx any, refreshToken any) *MockIAuth_RefreshToken_Call {
	return &MockIAuth_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockIAuth_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockIAuth_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAuth_RefreshToken_Call) Return(signInResult *SignInResult, err error) *MockIAuth_RefreshToken_Call {
	_c.Call.Return(signInResult, err)
	return _c
}

func (_c *MockIAuth_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*SignInResult, error)) *MockIAuth_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// SignIn provides a mock function for the type MockIAuth
func (_mock *MockIAuth) SignIn(ctx context.Context, email string, password string) (*SignInResult, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 *SignInResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*SignInResult, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *SignInResult); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SignInResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAuth_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type MockIAuth_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockIAuth_Expecter) SignIn(ctx any, email any, password any) *MockIAuth_SignIn_Call {
	return &MockIAuth_SignIn_Call{Call: _e.mock.On("SignIn", ctx, email, password)}
}

func (_c *MockIAuth_SignIn_Call) Run(run func(ctx context.Context, email string, password string)) *MockIAuth_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAuth_SignIn_Call) Return(signInResult *SignInResult, err error) *MockIAuth_SignIn_Call {
	_c.Call.Return(signInResult, err)
	return _c
}

func (_c *MockIAuth_SignIn_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*SignInResult, error)) *MockIAuth_SignIn_Call {
	_c.Call.Return(run)
	return _c
}

// SignOut provides a mock function for the type MockIAuth
func (_mock *MockIAuth) SignOut(ctx context.Context, accessToken string) error {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for SignOut")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAuth_SignOut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignOut'
type MockIAuth_SignOut_Call struct {
	*mock.Call
}

// SignOut is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockIAuth_Expecter) SignOut(ctx any, accessToken any) *MockIAuth_SignOut_Call {
	return &MockIAuth_SignOut_Call{Call: _e.mock.On("SignOut", ctx, accessToken)}
}

func (_c *MockIAuth_SignOut_Call) Run(run func(ctx context.Context, accessToken string)) *MockIAuth_SignOut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAuth_SignOut_Call) Return(err error) *MockIAuth_SignOut_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAuth_SignOut_Call) RunAndReturn(run func(ctx context.Context, accessToken string) error) *MockIAuth_SignOut_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function for the type MockIAuth
func (_mock *MockIAuth) SignUp(ctx context.Context, username string, password string) (*SignUpResult, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 *SignUpResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*SignUpResult, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *SignUpResult); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SignUpResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAuth_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockIAuth_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockIAuth_Expecter) SignUp(ctx any, username any, password any) *MockIAuth_SignUp_Call {
	return &MockIAuth_SignUp_Call{Call: _e.mock.On("SignUp", ctx, username, password)}
}

func (_c *MockIAuth_SignUp_Call) Run(run func(ctx context.Context, username string, password string)) *MockIAuth_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAuth_SignUp_Call) Return(signUpResult *SignUpResult, err error) *MockIAuth_SignUp_Call {
	_c.Call.Return(signUpResult, err)
	return _c
}

func (_c *MockIAuth_SignUp_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (*SignUpResult, error)) *MockIAuth_SignUp_Call {
	_c.Call.Return(run)
	return _c
}
