// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ehr

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIEHR creates a new instance of MockIEHR. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIEHR(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIEHR {
	mock := &MockIEHR{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIEHR is an autogenerated mock type for the IEHR type
type MockIEHR struct {
	mock.Mock
}

type MockIEHR_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIEHR) EXPECT() *MockIEHR_Expecter {
	return &MockIEHR_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockIEHR
func (_mock *MockIEHR) Authenticate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEHR_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockIEHR_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIEHR_Expecter) Authenticate(ctx any) *MockIEHR_Authenticate_Call {
	return &MockIEHR_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx)}
}

func (_c *MockIEHR_Authenticate_Call) Run(run func(ctx context.Context)) *MockIEHR_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEHR_Authenticate_Call) Return(err error) *MockIEHR_Authenticate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEHR_Authenticate_Call) RunAndReturn(run func(ctx context.Context) error) *MockIEHR_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// BookAppointment provides a mock function for the type MockIEHR
func (_mock *MockIEHR) BookAppointment(ctx context.Context, params BookAppointmentParams) (*BookedAppointment, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for BookAppointment")
	}

	var r0 *BookedAppointment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, BookAppointmentParams) (*BookedAppointment, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, BookAppointmentParams) *BookedAppointment); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*BookedAppointment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, BookAppointmentParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEHR_BookAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BookAppointment'
type MockIEHR_BookAppointment_Call struct {
	*mock.Call
}

// BookAppointment is a helper method to define mock.On call
//   - ctx context.Context
//   - params BookAppointmentParams
func (_e *MockIEHR_Expecter) BookAppointment(ctx any, params any) *MockIEHR_BookAppointment_Call {
	return &MockIEHR_BookAppointment_Call{Call: _e.mock.On("BookAppointment", ctx, params)}
}

func (_c *MockIEHR_BookAppointment_Call) Run(run func(ctx context.Context, params BookAppointmentParams)) *MockIEHR_BookAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 BookAppointmentParams
		if args[1] != nil {
			arg1 = args[1].(BookAppointmentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEHR_BookAppointment_Call) Return(bookedAppointment *BookedAppointment, err error) *MockIEHR_BookAppointment_Call {
	_c.Call.Return(bookedAppointment, err)
	return _c
}

func (_c *MockIEHR_BookAppointment_Call) RunAndReturn(run func(ctx context.Context, params BookAppointmentParams) (*BookedAppointment, error)) *MockIEHR_BookAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// CancelAppointment provides a mock function for the type MockIEHR
func (_mock *MockIEHR) CancelAppointment(ctx context.Context, params CancelAppointmentParams) (*CancelledAppointment, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CancelAppointment")
	}

	var r0 *CancelledAppointment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CancelAppointmentParams) (*CancelledAppointment, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CancelAppointmentParams) *CancelledAppointment); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CancelledAppointment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CancelAppointmentParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEHR_CancelAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelAppointment'
type MockIEHR_CancelAppointment_Call struct {
	*mock.Call
}

// CancelAppointment is a helper method to define mock.On call
//   - ctx context.Context
//   - params CancelAppointmentParams
func (_e *MockIEHR_Expecter) CancelAppointment(ctx any, params any) *MockIEHR_CancelAppointment_Call {
	return &MockIEHR_CancelAppointment_Call{Call: _e.mock.On("CancelAppointment", ctx, params)}
}

func (_c *MockIEHR_CancelAppointment_Call) Run(run func(ctx context.Context, params CancelAppointmentParams)) *MockIEHR_CancelAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CancelAppointmentParams
		if args[1] != nil {
			arg1 = args[1].(CancelAppointmentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEHR_CancelAppointment_Call) Return(cancelledAppointment *CancelledAppointment, err error) *MockIEHR_CancelAppointment_Call {
	_c.Call.Return(cancelledAppointment, err)
	return _c
}

func (_c *MockIEHR_CancelAppointment_Call) RunAndReturn(run func(ctx context.Context, params CancelAppointmentParams) (*CancelledAppointment, error)) *MockIEHR_CancelAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOnboarding provides a mock function for the type MockIEHR
func (_mock *MockIEHR) CreateOnboarding(ctx context.Context, params CreateOnboardingParams) (*Onboarding, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateOnboarding")
	}

	var r0 *Onboarding
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateOnboardingParams) (*Onboarding, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateOnboardingParams) *Onboarding); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Onboarding)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateOnboardingParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEHR_CreateOnboarding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOnboarding'
type MockIEHR_CreateOnboarding_Call struct {
	*mock.Call
}

// CreateOnboarding is a helper method to define mock.On call
//   - ctx context.Context
//   - params CreateOnboardingParams
func (_e *MockIEHR_Expecter) CreateOnboarding(ctx any, params any) *MockIEHR_CreateOnboarding_Call {
	return &MockIEHR_CreateOnboarding_Call{Call: _e.mock.On("CreateOnboarding", ctx, params)}
}

func (_c *MockIEHR_CreateOnboarding_Call) Run(run func(ctx context.Context, params CreateOnboardingParams)) *MockIEHR_CreateOnboarding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateOnboardingParams
		if args[1] != nil {
			arg1 = args[1].(CreateOnboardingParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEHR_CreateOnboarding_Call) Return(onboarding *Onboarding, err error) *MockIEHR_CreateOnboarding_Call {
	_c.Call.Return(onboarding, err)
	return _c
}

func (_c *MockIEHR_CreateOnboarding_Call) RunAndReturn(run func(ctx context.Context, params CreateOnboardingParams) (*Onboarding, error)) *MockIEHR_CreateOnboarding_Call {
	_c.Call.Return(run)
	return _c
}

// FindAppointment provides a mock function for the type MockIEHR
func (_mock *MockIEHR) FindAppointment(ctx context.Context, params AvailableAppointmentsParams) ([]Appointment, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for FindAppointment")
	}

	var r0 []Appointment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AvailableAppointmentsParams) ([]Appointment, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AvailableAppointmentsParams) []Appointment); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Appointment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AvailableAppointmentsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEHR_FindAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAppointment'
type MockIEHR_FindAppointment_Call struct {
	*mock.Call
}

// FindAppointment is a helper method to define mock.On call
//   - ctx context.Context
//   - params AvailableAppointmentsParams
func (_e *MockIEHR_Expecter) FindAppointment(ctx any, params any) *MockIEHR_FindAppointment_Call {
	return &MockIEHR_FindAppointment_Call{Call: _e.mock.On("FindAppointment", ctx, params)}
}

func (_c *MockIEHR_FindAppointment_Call) Run(run func(ctx context.Context, params AvailableAppointmentsParams)) *MockIEHR_FindAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AvailableAppointmentsParams
		if args[1] != nil {
			arg1 = args[1].(AvailableAppointmentsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEHR_FindAppointment_Call) Return(appointments []Appointment, err error) *MockIEHR_FindAppointment_Call {
	_c.Call.Return(appointments, err)
	return _c
}

func (_c *MockIEHR_FindAppointment_Call) RunAndReturn(run func(ctx context.Context, params AvailableAppointmentsParams) ([]Appointment, error)) *MockIEHR_FindAppointment_Call {
	_c.Call.Return(run)
	return _c
}
